### PR TITLE
Remove unused import statement

### PR DESCRIPTION
**Pull request by kurianbenoy**
* This is to fix flake 8 errors 
* Checkout the work happening here to understand the context of work:https://github.com/Cloud-CV/EvalAI/pull/2166

### CODE REVIEW

**Comment by deshraj** [comment]
It gets used actually in the `main.py` file. You might want to add `#noqa` in front of the line and then run the flake8 tests.

**Comment by kurianbenoy** [comment]
Made the requested change

**Comment by RishabhJain2018** [comment]
Rather than testing flake8 locally, I'd suggest adding black and flake8 as a pre-commit hook.

**Comment by kurianbenoy** [comment]
> Rather than testing flake8 locally, I'd suggest adding black and flake8 as a pre-commit hook.

Okay Rishab, I will update the PR with that soon.

**Comment by kurianbenoy** [comment]
@RishabhJain2018 I have updated the PR by adding a pre-commit hook for this repo

**Comment by RishabhJain2018** [comment]
Thanks @kurianbenoy for adding it.

**Comment by kurianbenoy** [comment]
@deshraj and @RishabhJain2018 do review when free

**Pull request closed without merging**
